### ISSUE TITLE
website: improve full-size image zoom

### ISSUE THREAD

**Issue by sophiapoirier** [sophiapoirier/destroyfx#15]
I'm adding a couple of issues for @tom7 that I found notes about while reorganizing the "extras" page, and which both were actually things that I had also been meaning to ask you about.

This one is the full-size image zoom that happens when you click on a plugin's thumbnail image.  I saw your comments:
```
    function FullImage(f) {
      // XXX improve!
      window.location = f;
    }
```
I'm not sure what exactly you were thinking in terms of improvements, but I was thinking it would be nicer if the full-size image appeared as an overlay in the current browser window/tab rather than in a new window (as I implemented it so many years ago with my novice javascript chops).  Opening a new window for an image feels kinda hostile to the 21st century web browsing experience.  Plus crops the bottom and looks bad in Safari (and perhaps other browsers, but not Chrome).

**Comment by sophiapoirier** [comment]
I actually gave a little bit of a try myself a while back, following [these steps](https://www.sylvaindurand.org/overlay-image-in-pure-css/), but I couldn't get it to work.

**Comment by tom7** [comment]
Yeah, in-page overlay is what I meant. Should not be hard; the direct link is just a placeholder.

**Comment by tom7** [comment]
Gave this a shot in 93dcab1451ac0ff92e0e849e9bbda7479d7031f6. I'm not 100% on whether this works correctly wrt back button (when the image is open, both clicking and 'back button' should take you back to index.html and remove the unsightly '#' from the URL) in all browsers, so pls reopen if you notice something amiss. I didn't push the site to destroyfx.org.
Would be nice to disable scrolling and allow something like escape to close the overlay, but these are a bit more invasive because they require window-level event handlers and then cleanup. In any case, should be a big improvement over the current just-link-to-image behavior.

**Comment by sophiapoirier** [comment]
Awesome!  Looks and works great for me on Safari and Chrome on Mac.  Escape hook sounds like gravy to me, certainly not essential if it's annoyingly complicated.  And the scrolling... I mean is it even "wrong"?  Doesn't bother me personally.  It is so much improved!

**Comment by tom7** [comment]
Great, thanks for verifying!
Agreed on both esc / scroll.

**Comment by sophiapoirier** [comment]
I pushed to server so I could try on iPhone and iPad and is 👌 there too.
